import { useState } from 'react'

type SlotProps = {
  label: string
  description: string
  configured?: boolean
}

function UnconfiguredSlot({ label, description }: SlotProps) {
  const [hovered, setHovered] = useState(false)
  return (
    <div
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}
      style={{
        flex: 1,
        border: `2px dashed ${hovered ? '#64748b' : '#cbd5e1'}`,
        borderRadius: 10,
        padding: '20px 16px',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        gap: 8,
        cursor: 'pointer',
        background: hovered ? '#f8fafc' : '#fff',
        transition: 'border-color .15s, background .15s',
        minWidth: 0,
      }}
    >
      <div style={{ fontWeight: 600, fontSize: 14, color: '#1e293b' }}>{label}</div>
      <div style={{ fontSize: 12, color: '#94a3b8', textAlign: 'center', lineHeight: 1.4 }}>{description}</div>
      <div style={{
        marginTop: 8,
        fontSize: 11,
        fontWeight: 600,
        textTransform: 'uppercase',
        letterSpacing: '.06em',
        color: hovered ? '#3b82f6' : '#cbd5e1',
        transition: 'color .15s',
      }}>
        + Configure
      </div>
    </div>
  )
}

function SectionLabel({ children }: { children: string }) {
  return (
    <div style={{
      fontSize: 10,
      fontWeight: 700,
      textTransform: 'uppercase',
      letterSpacing: '.1em',
      color: '#94a3b8',
      marginBottom: 12,
    }}>
      {children}
    </div>
  )
}

function FlowArrow() {
  return (
    <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: 36 }}>
      <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 0 }}>
        <div style={{ width: 2, height: 20, background: '#cbd5e1' }} />
        <div style={{
          width: 0,
          height: 0,
          borderLeft: '6px solid transparent',
          borderRight: '6px solid transparent',
          borderTop: '8px solid #cbd5e1',
        }} />
      </div>
    </div>
  )
}

const APPLIANCE_SLOTS = [
  'Appliance 1',
  'Appliance 2',
  'Appliance 3',
  'Appliance 4',
  'Appliance 5',
]

function Home() {
  return (
    <div style={{ padding: '32px 40px', maxWidth: 900, margin: '0 auto' }}>

      {/* Inputs */}
      <section>
        <SectionLabel>Inputs</SectionLabel>
        <div style={{ display: 'flex', gap: 16 }}>
          <UnconfiguredSlot
            label="Grid"
            description="Device measuring power imported from or exported to the grid"
          />
          <UnconfiguredSlot
            label="Solar Inverter"
            description="Device measuring power generated by your solar panels"
          />
        </div>
      </section>

      <FlowArrow />

      {/* Consumer Unit */}
      <section style={{ display: 'flex', justifyContent: 'center' }}>
        <div style={{
          border: '2px solid #1e293b',
          borderRadius: 10,
          padding: '16px 48px',
          textAlign: 'center',
          background: '#fff',
          minWidth: 200,
        }}>
          <div style={{ fontWeight: 700, fontSize: 14, color: '#1e293b' }}>Consumer Unit</div>
          <div style={{ fontSize: 12, color: '#64748b', marginTop: 4 }}>Main distribution board</div>
        </div>
      </section>

      <FlowArrow />

      {/* Loads */}
      <section>
        <SectionLabel>Loads</SectionLabel>
        <div style={{ display: 'flex', gap: 12 }}>
          {APPLIANCE_SLOTS.map(name => (
            <UnconfiguredSlot
              key={name}
              label={name}
              description="Assign a device to monitor this load"
            />
          ))}
        </div>
      </section>

    </div>
  )
}

export default Home
